### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by sbonaime** [juanmcasillas/gopro2gpx#16]
After installation with 
`pip install git+https://github.com/juanmcasillas/gopro2gpx`
On my mac 11.3 I have this error
````
gopro2gpx -s GH011227_saut.MP4 test
GPSFIX change to 3 [lock 3D (ok)]
-- stats -----------------
- Ok:                202
- GPSFIX=0 (bad):      0 (skipped: 0)
- Empty (No data):     0
Total points:        202
--------------------------
Traceback (most recent call last):
  File "/usr/local/bin/gopro2gpx", line 33, in <module>
    sys.exit(load_entry_point('gopro2gpx==0.1', 'console_scripts', 'gopro2gpx')())
TypeError: 'module' object is not callable
````
gpx and kml are created but the speed is off of more than 300km/h ! 
With the same file in https://goprotelemetryextractor.com/free/ I can see that I don't have any gps problems and the speed is correct. 
Any ideas ? 
Thanks

**Comment by Simske** [comment]
Hi, the the `TypeError` should be fixed by #15, maybe try to install from the PR, but I'm confused why it ran anyway.

As to the speed problem I have no idea what is wrong there. Is only the speed messed up, or are the coordinates also wrong?

**Comment by sbonaime** [comment]
#15  fix the error thanks. 
I still have some weird speed and vertical speed. I will make a new issue
<img width="409" alt="Capture d’écran 2021-05-04 à 04-05-21 14 49 05" src="https://user-images.githubusercontent.com/750709/117005842-01f29f80-ace8-11eb-9482-f829e4d68d53.png">
